# default editor
preferred_editor=nvim
if type "$preferred_editor" &> /dev/null; then
  export VISUAL="$preferred_editor"
  export EDITOR="$preferred_editor"
fi

if type nvim &> /dev/null; then
  alias vi=nvim
  alias vim=nvim
fi

# autocomplete
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# ls colors
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

# short mimjava alias
shopt -s cdable_vars
export mj=$HOME/mim-workspace/stable/mimjava
export r71=$HOME/mim-workspace/release-7.1/mimjava
export r70=$HOME/mim-workspace/release-7.0/mimjava
export r69=$HOME/mim-workspace/release-6.9/mimjava
export r68=$HOME/mim-workspace/release-6.8/mimjava

# home bin (custom commands)
export PATH="$HOME/bin:$PATH"

# coreutils
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

# arc stuff
export PATH="$HOME/tools/arcanist/bin:$PATH"

# python3 symlink overrides
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# Path to the bash it configuration
export BASH_IT="$HOME/.bash_it"

# Lock and Load a custom theme file
# location /.bash_it/themes/
export THEME_CHECK_SUDO=false
export BASH_IT_THEME='powerline-multiline'


# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Load Bash It
source "$BASH_IT"/bash_it.sh

# Rust
export PATH="$HOME/.cargo/bin:$PATH"
