" vim-plug
call plug#begin('~/.config/nvim')
Plug 'dracula/vim'
Plug 'JamshedVesuna/vim-markdown-preview'
Plug 'rust-lang/rust.vim'
Plug 'elixir-editors/vim-elixir'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'dense-analysis/ale'
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
call plug#end()

" colors
color dracula

" vim-markdown-preview
let vim_markdown_preview_github = 1 " use github-style markdown

" .pl is always prolog (never perl)
au FileType perl set filetype=prolog

" Enable syntax highlighting
syntax on

" Airline
let g:airline_powerline_fonts = 1

" ale
let g:ale_cursor_detail = 1
let g:ale_floating_preview = 1

" misc.
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set backspace=indent,eol,start
set number
set cursorline
set showmatch
set incsearch
set linebreak

