##################
# Custom (early) #
##################

# Custom completion (here because it must be done before compinit)
# via https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

# Jenv (up here because it can produce console output)
path+=$HOME/.jenv/bin
eval "$(jenv init -)"

#################
# Powerlevel10k #
#################

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  mercurial
  zsh-syntax-highlighting
  zsh-autosuggestions
  wd
)

# oh-my-zsh wants to change the permissions of certain autocomplete
# directories, but I work on some machines without such permissions. Don't
# run the check in this case.
limited_permission_machines=(
  "attila.mimsoftware.com"
)

if (($limited_permission_machines[(Ie)$(hostname)])); then
  ZSH_DISABLE_COMPFIX=true
fi

# In the event that an update is available, oh-my-zsh will ask if we want to
# update via interactive prompt. This is a problem for IntelliJ when it loads
# its terminal, so we disable the prompt in this case.
# https://youtrack.jetbrains.com/articles/IDEA-A-19/Shell-Environment-Loading
if [ -n "$INTELLIJ_ENVIRONMENT_READER" ]; then
  DISABLE_UPDATE_PROMPT=true
fi

# Main oh-my-zsh config
source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias pip="python3 -m pip"
alias python="python3"

if type "nvim" &> /dev/null; then
  alias vi="nvim"
  alias vim="nvim"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

##########
# Custom #
##########

# PATH
path+=$HOME/bin
path+=$HOME/.cargo/bin
path+=/usr/local/opt/coreutils/libexec/gnubin
path+=$HOME/tools/arcanist/bin
path+=$HOME/.jenv/bin
path+=/opt/homebrew/opt/python@3.10/bin
path+=/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin
path+=/opt/homebrew/opt/php@8.0/bin
path+=/opt/homebrew/opt/php@8.0/sbin
path+=/usr/local/opt/php@8.0/bin
path+=/usr/local/opt/php@8.0/sbin

# Default editor
preferred_editor=nvim
if type "$preferred_editor" &> /dev/null; then
  export VISUAL="$preferred_editor"
  export EDITOR="$preferred_editor"
fi

# Enable Mercurial VCS info (wizard will disable by default because it's slow)
typeset -g POWERLEVEL9K_VCS_BACKENDS=(git hg)

# MIM logo instead of OS symbol (for work computers--requires patched font)
work_computers=(
  "MVC0621"
  "MVC0621.local"
  "MVC1029"
  "MVC1029.local"
  "attila.mimsoftware.com"
)
if (($work_computers[(Ie)$(hostname)])); then
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=''
fi

# Shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# WSL stuff
if uname -r | grep -iq 'Microsoft' ; then
  # Named PC home dir
  [[ "Zach-PC" =~ "$(hostname)" ]] && hash -d win=/mnt/c/Users/zach

  # Browser var
  export BROWSER=wslview

  # open command (normal `open` doesn't exist for WSL)
  function open () {
    if [ ! -z $1 ]; then
      winpath=$(readlink -m $1)
    else
      winpath=$(pwd)
    fi
    winpath=`echo $winpath | sed 's/\/mnt\/c\//C:\//g'`
    winpath=`echo $winpath | sed 's/\//\\\\/g'`
    explorer.exe $winpath
  }
fi

